local base=require("clients.admin_v20")
local M={}
for k,v in pairs(base)do M[k]=v end
local C={bg=colors.black,text=colors.white,dim=colors.lightGray,good=colors.lime,warn=colors.orange,panel=colors.gray}
local function nice(v)return tostring(v or""):upper():gsub("MINECRAFT:",""):gsub("[_%-]"," ")end
local function state(env)return env and env.state or{}end
local function hasCategory(d,w)for _,v in ipairs(d and d.categories or{})do if v==w then return true end end;return false end
local function isMonitor(n)local ok,t=pcall(peripheral.getType,n);if ok and t=="monitor"then return true end;if type(peripheral.hasType)=="function"then local ok2,v=pcall(peripheral.hasType,n,"monitor");if ok2 and v then return true end end;return false end
local function mons()local out={};local ok,names=pcall(peripheral.getNames);if not ok or type(names)~="table"then return out end;for _,n in ipairs(names)do if isMonitor(n)then local okW,m=pcall(peripheral.wrap,n);if okW and m then local scale=1;pcall(m.setTextScale,scale);local okS,w,h=pcall(m.getSize);if okS then w,h=tonumber(w),tonumber(h);if w<22 or h<12 then scale=.5;pcall(m.setTextScale,scale);local ok2,w2,h2=pcall(m.getSize);if ok2 then w,h=tonumber(w2)or w,tonumber(h2)or h end end;out[#out+1]={name=n,mon=m,w=w,h=h,scale=scale,area=w*h}end end end end;table.sort(out,function(a,b)if a.area~=b.area then return a.area>b.area end;if a.w~=b.w then return a.w>b.w end;return a.name<b.name end);return out end
local function put(e,x,y,s,c)if y<1 or y>e.h then return end;s=tostring(s or"");e.mon.setCursorPos(math.max(1,x),y);e.mon.setTextColor(c or C.text);e.mon.setBackgroundColor(C.bg);e.mon.write(s:sub(1,math.max(0,e.w-x+1)))end
local function prep(e)e.mon.setBackgroundColor(C.bg);e.mon.setTextColor(C.text);e.mon.clear()end
local function pop(list,score)local bi,bs=nil,-math.huge;for i,e in ipairs(list)do local s=score(e);if s>bs then bi,bs=i,s end end;return bi and table.remove(list,bi)or nil end
local function sensors(env)local a=state(env).attachments or{};local out,seen={},{};local function add(d)local n=tostring(d.type or""):lower();local jt=table.concat(d.types or{}," "):lower();if n:find("block_reader",1,true)or n:find("blockreader",1,true)or jt:find("me_bridge",1,true)then return end;if not(hasCategory(d,"sensor")or hasCategory(d,"sensor_candidate"))then return end;local k=tostring(d._source or"").."|"..tostring(d.name or d.type);if not seen[k]then seen[k]=true;out[#out+1]=d end end;for _,d in ipairs(a.devices or{})do add(d)end;for _,d in ipairs(a.sensors or{})do add(d)end;table.sort(out,function(a,b)return tostring(a.name or a.type)<tostring(b.name or b.type)end);return out end
local function drawSensor(e,s,idx,total)prep(e);put(e,2,1,"SENSOR "..idx.."/"..total,C.text);put(e,2,3,string.rep("-",math.max(0,e.w-2)),C.panel);put(e,2,5,nice(s.reportedName or s.name or s.type),C.text);if s._source then put(e,2,6,"NODE "..tostring(s._source),C.dim)end;put(e,2,8,nice(s.summary or"ONLINE"),C.good);local m=s.metrics or{};local y=10;for _,r in ipairs({{"TEMP",m.temperature},{"HUMIDITY",m.humidity},{"PRESSURE",m.pressure},{"PLAYERS",m.onlinePlayers or m.playerCount},{"ENTITIES",m.entityCount},{"RADIATION",m.radiationRaw or m.radiationText}})do if r[2]~=nil and y<=e.h then put(e,2,y,r[1],C.dim);if y+1<=e.h then put(e,2,y+1,tostring(r[2]),C.text)end;y=y+3 end end end
local function drawSystems(e,env)prep(e);put(e,2,1,"KIMI SYSTEMS",C.text);put(e,2,3,string.rep("-",math.max(0,e.w-2)),C.panel);local s=state(env);put(e,2,5,"VERSION",C.dim);put(e,2,6,tostring(env and env.version or"?"),C.text);put(e,2,9,"AE2 "..((s.ae2 and s.ae2.online)and"ONLINE"or"OFFLINE"),C.text);put(e,2,11,"BUILDER "..((s.builder and s.builder.online)and"ONLINE"or"OFFLINE"),C.text);put(e,2,13,"WEATHER "..tostring(s.environment and s.environment.weather or"?"),C.text)end
function M.render(env,meta)local ok=base.render(env,meta);local all=mons();local extra={};for i=4,#all do extra[#extra+1]=all[i]end;if #extra==0 then return ok end;pop(extra,function(e)return(e.w/math.max(1,e.h))*1000+e.area end);local ae=state(env).ae2 or{};if #extra>0 and(ae.online or ae.connected or ae.bridge)then pop(extra,function(e)return e.area end)end;local b=state(env).builder or{};if #extra>0 and(b.online or b.primary or(b.builders and#b.builders>0))then pop(extra,function(e)return e.area end)end;local ss=sensors(env);local rot=math.floor(((os.epoch and os.epoch("utc")or 0)/6000));for i,e in ipairs(extra)do if i>#ss then drawSystems(e,env)else local idx;if #ss<=#extra then idx=i else idx=((rot+i-2)%#ss)+1 end;drawSensor(e,ss[idx],idx,#ss)end end;return ok end
return M
